const OPENROUTER="https://openrouter.ai/api/v1",NVIDIA="https://integrate.api.nvidia.com/v1";
const items=[];let running=false,processing=false,pendingAudio=null,lastError="",currentMode="browser",captureTabId=null;
const settings=()=>chrome.storage.local.get(["openrouterKey","nvidiaKey","speechMode"]);
async function request(url,key,body){const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||d.detail||`API ${r.status}`);return d}
async function nvidia(text,from,to){const {nvidiaKey}=await settings();if(!nvidiaKey)throw new Error("請先儲存 NVIDIA Key");const d=await request(`${NVIDIA}/chat/completions`,nvidiaKey,{model:"nvidia/riva-translate-4b-instruct-v2",messages:[{role:"system",content:`${from}-${to}`},{role:"user",content:text}],temperature:0,max_tokens:300});return(d.choices?.[0]?.message?.content||"").trim()}
async function freeTranslate(text,from,to){try{const q=new URLSearchParams({q:text,langpair:`${from}|${to}`});const r=await fetch(`https://api.mymemory.translated.net/get?${q}`);const d=await r.json().catch(()=>({}));if(!r.ok||d.responseStatus!==200)throw new Error(d.responseDetails||`免費翻譯 API ${r.status}`);return(d.responseData?.translatedText||"").trim()}catch(_error){const q=new URLSearchParams({client:"gtx",sl:from,tl:to,dt:"t",q:text});const r=await fetch(`https://translate.googleapis.com/translate_a/single?${q}`);if(!r.ok)throw new Error(`免費翻譯 API ${r.status}`);const d=await r.json();return(d[0]||[]).map(x=>x[0]||"").join("").trim()}}
async function translate(text,direction,allowFree=true){if(direction==="ja-zh"){if(allowFree){try{const result=await freeTranslate(text,"ja","zh-TW");if(/[\u3400-\u9fff]/.test(result))return result}catch(_error){}}const result=await nvidia(text,"ja","zh-tw");if(!/[\u3400-\u9fff]/.test(result))throw new Error("翻譯服務未回傳中文");return result}const {openrouterKey}=await settings();if(!openrouterKey)return freeTranslate(text,"zh-TW","ja");try{const d=await request(`${OPENROUTER}/chat/completions`,openrouterKey,{model:"google/gemma-4-31b-it:free",messages:[{role:"system",content:"將中文翻成適合對日本 VTuber 留言的自然日文。親切、柔和、有一點可愛並保持禮貌；忠實保留原意，不擅自增加稱呼、告白或表情。只輸出可直接貼出的日文。"},{role:"user",content:text}],temperature:0,max_tokens:300});return(d.choices?.[0]?.message?.content||"").trim()}catch(_error){return freeTranslate(text,"zh-TW","ja")}}
async function transcribe(base64,format){const {openrouterKey}=await settings();if(!openrouterKey)throw new Error("請先儲存 OpenRouter Key");const d=await request(`${OPENROUTER}/audio/transcriptions`,openrouterKey,{model:"nvidia/nemotron-3.5-asr-streaming-multilingual-0.6b",input_audio:{data:base64,format},language:"ja",temperature:0});return(d.text||"").trim()}
function pushSubtitle(item){if(captureTabId)chrome.tabs.sendMessage(captureTabId,{type:"subtitle-update",item}).catch(()=>{})}
function comparable(text){return String(text).toLowerCase().replace(/[\s、。，,.!?！？・…「」『』（）()\[\]]/g,"")}
function bigrams(text){const result=new Set;for(let i=0;i<text.length-1;i++)result.add(text.slice(i,i+2));return result}
function isRepeatedTranscript(original){const current=comparable(original),previous=comparable(items.at(-1)?.original||"");if(!current||current===previous)return true;if(current.length<5||previous.length<5)return false;const lengthRatio=Math.min(current.length,previous.length)/Math.max(current.length,previous.length);if(lengthRatio<.75)return false;const a=bigrams(current),b=bigrams(previous);let shared=0;for(const part of a)if(b.has(part))shared++;return shared/Math.max(1,Math.min(a.size,b.size))>.84}
async function addTranscript(original){if(!original||isRepeatedTranscript(original))return;const item={id:Date.now(),original,translated:"(translating...)",updatedAt:Date.now()/1000};items.push(item);if(items.length>20)items.shift();pushSubtitle(item);try{item.translated=await translate(original,"ja-zh");lastError=""}catch(e){item.translated="翻譯暫時無法使用";lastError=e.message}item.updatedAt=Date.now()/1000;pushSubtitle(item)}
async function processAudio(audio){if(processing){pendingAudio=audio;return}processing=true;try{await addTranscript(await transcribe(audio.base64,audio.format))}catch(e){lastError=e.message}finally{processing=false;if(pendingAudio){const next=pendingAudio;pendingAudio=null;processAudio(next)}}}
async function ensureOffscreen(){if(await chrome.offscreen.hasDocument())return;await chrome.offscreen.createDocument({url:"offscreen.html",reasons:["USER_MEDIA"],justification:"擷取目前分頁聲音以產生即時字幕"})}
async function startCapture(tabId){const k=await settings(),mode=k.speechMode||"browser";currentMode=mode;captureTabId=tabId;if(mode==="cloud"&&!k.openrouterKey)throw new Error("雲端模式需要 OpenRouter Key");await ensureOffscreen();const streamId=await chrome.tabCapture.getMediaStreamId({targetTabId:tabId});items.length=0;lastError="";const reply=await chrome.runtime.sendMessage({type:"offscreen-start",streamId,mode});if(!reply?.ok)throw new Error(reply?.error||"無法擷取目前分頁的聲音");running=true;return{running}}
async function stopCapture(){running=false;lastError="";pendingAudio=null;await chrome.runtime.sendMessage({type:"offscreen-stop"}).catch(()=>{});return{running}}
chrome.runtime.onMessage.addListener((m,s,send)=>{if(m.type==="audio-chunk"){if(currentMode==="cloud")processAudio(m);send({ok:true});return}if(m.type==="speech-result"){if(currentMode==="browser")addTranscript(m.text);send({ok:true});return}if(m.type==="model-status"){lastError=m.text;send({ok:true});return}if(m.type==="speech-error"){lastError=m.error==="not-allowed"?"瀏覽器未允許免費語音辨識":m.error==="network"?"免費模型目前無法連線":m.error;send({ok:true});return}let task;if(m.type==="translate")task=translate(m.text,m.direction,Boolean(m.priority));else if(m.type==="subtitles")task=Promise.resolve({running,items});else if(m.type==="health")task=settings().then(k=>({running,configured:Boolean((k.speechMode||"browser")==="browser"||k.openrouterKey),speechMode:k.speechMode||"browser",hasOpenrouter:Boolean(k.openrouterKey),hasNvidia:Boolean(k.nvidiaKey),lastError,itemCount:items.length,lastOriginal:items.at(-1)?.original||"",lastTranslated:items.at(-1)?.translated||""}));else if(m.type==="subtitle-control")task=m.action==="stop"?stopCapture():startCapture(m.tabId||s.tab?.id);else if(m.type==="save-keys")task=settings().then(k=>chrome.storage.local.set({openrouterKey:m.openrouterKey||k.openrouterKey||"",nvidiaKey:m.nvidiaKey||k.nvidiaKey||"",speechMode:m.speechMode||"browser"})).then(()=>true);else return;Promise.resolve(task).then(text=>send({ok:true,text})).catch(e=>send({ok:false,error:e.message}));return true});
